const actionTypes = {
  /* AUTH */
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  /* USER */
  EDIT_CURRENT_USER_REQUEST: "EDIT_CURRENT_USER_REQUEST",
  EDIT_CURRENT_USER_SUCCESS: "EDIT_CURRENT_USER_SUCCESS",
  EDIT_CURRENT_USER_FAILURE: "EDIT_CURRENT_USER_FAILURE",
  FETCH_CURRENT_USER_REQUEST: "FETCH_CURRENT_USER_REQUEST",
  FETCH_CURRENT_USER_SUCCESS: "FETCH_CURRENT_USER_SUCCESS",
  FETCH_CURRENT_USER_FAILURE: "FETCH_CURRENT_USER_FAILURE",
  CHANGE_PASSWORD_REQUEST: "CHANGE_PASSWORD_REQUEST",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_FAILURE: "CHANGE_PASSWORD_FAILURE",
  SET_CURRENT_USER: "SET_CURRENT_USER",
  JWT_DECODE_CURRENT_USER: "JWT_DECODE_CURRENT_USER",

  /* MODALS */
  OPEN_MODAL: "OPEN_MODAL",
  SHOW_MODAL: "SHOW_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",

  /* PLAYER */
  PLAY_PLAYER: "PLAY_PLAYER",
  PAUSE_PLAYER: "PAUSE_PLAYER",
  REPLAY_PLAYER: "REPLAY_PLAYER",
  POSITION_CHANGE_PLAYER: "POSITION_CHANGE_PLAYER",
  VOLUME_CHANGE_PLAYER: "VOLUME_CHANGE_PLAYER",

  /* SONGS */
  REQUEST_SEARCH_TRACKS: "REQUEST_SEARCH_TRACKS",
  RECEIVE_SEARCH_TRACKS: "RECEIVE_SEARCH_TRACKS",
  SEARCH_TRACKS: "SEARCH_TRACKS",
  CLEAR_SEARCH_RESULTS: "CLEAR_SEARCH_RESULTS",
  CHANGE_SEARCH_TITLE: "CHANGE_SEARCH_TITLE",
  REQUEST_FETCH_TRACK: "REQUEST_FETCH_TRACK",
  RECEIVE_FETCHED_TRACK: "RECEIVE_FETCHED_TRACK",
  SET_SEARCH_MIN_TEMPO: "SET_SEARCH_MIN_TEMPO",
  SET_SEARCH_MAX_TEMPO: "SET_SEARCH_MAX_TEMPO",
  PLAY_TRACK: "PLAY_TRACK",
  SEARCH_TRACKS_BY_CURRENT_FILTERS: "SEARCH_TRACKS_BY_CURRENT_FILTERS",
  FETCH_HOT_TRACKS: "FETCH_HOT_TRACKS",
  SET_TRACK: "SET_TRACK",
  SET_HOT_TRACKS: "SET_HOT_TRACKS",
  SET_ACTIVE_VERSION: "SET_ACTIVE_VERSION",

  /* FILTERS */
  FETCH_SEARCH_FILTERS_DATA: "FETCH_SEARCH_FILTERS_DATA",
  REQUEST_SEARCH_FILTERS_DATA: "REQUEST_SEARCH_FILTERS_DATA",
  RECEIVE_SEARCH_FILTERS_DATA: "RECEIVE_SEARCH_FILTERS_DATA",
  SET_CURRENT_FILTERS_TAGS: "SET_CURRENT_FILTERS_TAGS",
  SET_CURRENT_FILTERS_TAGS_AND_SEARCH: "SET_CURRENT_FILTERS_TAGS_AND_SEARCH",

  /* TRACKS_QUEUE */
  SET_TRACKS_QUEUE: "SET_TRACKS_QUEUE",
  ADD_TO_QUEUE: "ADD_TO_QUEUE",
  REMOVE_FROM_QUEUE: "REMOVE_FROM_QUEUE",

  /*PLAYLISTS*/
  REQUEST_SEARCH_PLAYLISTS: "REQUEST_SEARCH_PLAYLISTS",
  RECEIVE_SEARCH_PLAYLISTS: "RECEIVE_SEARCH_PLAYLISTS",
  REQUEST_CREATE_PLAYLIST: "REQUEST_CREATE_PLAYLIST",
  RECEIVE_CREATE_PLAYLIST: "RECEIVE_CREATE_PLAYLIST",
  REQUEST_RENAME_PLAYLIST: "REQUEST_RENAME_PLAYLIST",
  RECEIVE_RENAME_PLAYLIST: "RECEIVE_RENAME_PLAYLIST",
  REQUEST_REMOVE_PLAYLIST: "REQUEST_REMOVE_PLAYLIST",
  RECEIVE_REMOVE_PLAYLIST: "RECEIVE_REMOVE_PLAYLIST",
  REQUEST_ADD_TO_PLAYLIST: "REQUEST_ADD_TO_PLAYLIST",
  RECEIVE_ADD_TO_PLAYLIST: "RECEIVE_ADD_TO_PLAYLIST",
  REQUEST_REMOVE_FROM_PLAYLIST: "REQUEST_REMOVE_FROM_PLAYLIST",
  RECEIVE_REMOVE_FROM_PLAYLIST: "RECEIVE_REMOVE_FROM_PLAYLIST",
  SET_ACTIVE_PERSONAL_PLAYLIST: "SET_ACTIVE_PERSONAL_PLAYLIST",
  SET_ACTIVE_HOT_PLAYLIST: "SET_ACTIVE_HOT_PLAYLIST",
  REQUEST_SHARED_PLAYLIST: "REQUEST_SHARED_PLAYLIST",
  RECEIVE_SHARED_PLAYLIST: "RECEIVE_SHARED_PLAYLIST",
  REQUEST_HOT_PLAYLISTS: "REQUEST_HOT_PLAYLISTS",
  RECEIVE_HOT_PLAYLISTS: "RECEIVE_HOT_PLAYLISTS",
  REQUEST_COPY_PLAYLIST: "REQUEST_COPY_PLAYLIST",
  RECEIVE_COPY_PLAYLIST: "RECEIVE_COPY_PLAYLIST",

  /*ARTISTS*/
  REQUEST_FETCH_ARTIST: "REQUEST_FETCH_ARTIST",
  RECEIVE_FETCH_ARTIST: "RECEIVE_FETCH_ARTIST",

  /*ERRORS*/
  SHOW_POPUP: "SHOW_POPUP",
  HIDE_POPUP: "HIDE_POPUP"
}

export default actionTypes
